apiVersion: v1
kind: Namespace
metadata:
  name: cloud-native-project
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: cloud-native-project
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "15"